// ═══════════════════════════════════════════════════════════════
//  Achievement Registry — 33 achievements
//  Types are imported from @/types (single source of truth).
//  Re-exported here for backwards compatibility.
// ═══════════════════════════════════════════════════════════════

export type { AchievementRarity, AchievementCategory, Achievement } from '@/types'
import type { Achievement } from '@/types'


export const ACHIEVEMENTS: Achievement[] = [
  // ── STREAK achievements ──────────────────────────────────────
  {
    id: 'streak_3',
    icon: '🔥',
    title: 'On Fire',
    description: 'Maintain a 3-day streak.',
    category: 'streak',
    rarity: 'common',
    xp_reward: 25,
    condition: { type: 'streak_days', threshold: 3 },
  },
  {
    id: 'streak_7',
    icon: '⚡',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak.',
    category: 'streak',
    rarity: 'common',
    xp_reward: 50,
    condition: { type: 'streak_days', threshold: 7 },
  },
  {
    id: 'streak_14',
    icon: '💥',
    title: 'Two Weeks Strong',
    description: 'Maintain a 14-day streak.',
    category: 'streak',
    rarity: 'rare',
    xp_reward: 100,
    condition: { type: 'streak_days', threshold: 14 },
  },
  {
    id: 'streak_21',
    icon: '🏆',
    title: 'Habit Former',
    description: 'Maintain a 21-day streak.',
    category: 'streak',
    rarity: 'rare',
    xp_reward: 150,
    condition: { type: 'streak_days', threshold: 21 },
  },
  {
    id: 'streak_30',
    icon: '👑',
    title: 'Iron Will',
    description: 'Maintain a 30-day streak.',
    category: 'streak',
    rarity: 'epic',
    xp_reward: 250,
    condition: { type: 'streak_days', threshold: 30 },
  },
  {
    id: 'streak_60',
    icon: '💎',
    title: 'Diamond Discipline',
    description: 'Maintain a 60-day streak.',
    category: 'streak',
    rarity: 'epic',
    xp_reward: 400,
    condition: { type: 'streak_days', threshold: 60 },
  },
  {
    id: 'streak_90',
    icon: '🌟',
    title: 'Legend in the Making',
    description: 'Maintain a 90-day streak.',
    category: 'streak',
    rarity: 'legendary',
    xp_reward: 750,
    condition: { type: 'streak_days', threshold: 90 },
  },

  // ── HABITS completed ─────────────────────────────────────────
  {
    id: 'habits_1',
    icon: '🌱',
    title: 'First Step',
    description: 'Complete your first habit.',
    category: 'habits',
    rarity: 'common',
    xp_reward: 10,
    condition: { type: 'habits_completed', threshold: 1 },
  },
  {
    id: 'habits_10',
    icon: '🎯',
    title: 'Momentum',
    description: 'Complete 10 habits total.',
    category: 'habits',
    rarity: 'common',
    xp_reward: 30,
    condition: { type: 'habits_completed', threshold: 10 },
  },
  {
    id: 'habits_50',
    icon: '⚔️',
    title: 'Battle Ready',
    description: 'Complete 50 habits total.',
    category: 'habits',
    rarity: 'rare',
    xp_reward: 75,
    condition: { type: 'habits_completed', threshold: 50 },
  },
  {
    id: 'habits_100',
    icon: '🏅',
    title: 'Century Club',
    description: 'Complete 100 habits total.',
    category: 'habits',
    rarity: 'rare',
    xp_reward: 150,
    condition: { type: 'habits_completed', threshold: 100 },
  },
  {
    id: 'habits_250',
    icon: '🚀',
    title: 'Elite Performer',
    description: 'Complete 250 habits total.',
    category: 'habits',
    rarity: 'epic',
    xp_reward: 300,
    condition: { type: 'habits_completed', threshold: 250 },
  },
  {
    id: 'habits_500',
    icon: '🌊',
    title: 'Unstoppable',
    description: 'Complete 500 habits total.',
    category: 'habits',
    rarity: 'epic',
    xp_reward: 500,
    condition: { type: 'habits_completed', threshold: 500 },
  },
  {
    id: 'habits_1000',
    icon: '🔱',
    title: 'Zenith Master',
    description: 'Complete 1,000 habits total.',
    category: 'habits',
    rarity: 'legendary',
    xp_reward: 1000,
    condition: { type: 'habits_completed', threshold: 1000 },
  },

  // ── PERFECT DAYS ─────────────────────────────────────────────
  {
    id: 'perfect_1',
    icon: '✨',
    title: 'Perfect Day',
    description: 'Complete all habits on a single day.',
    category: 'habits',
    rarity: 'common',
    xp_reward: 20,
    condition: { type: 'perfect_days', threshold: 1 },
  },
  {
    id: 'perfect_7',
    icon: '🌟',
    title: 'Perfect Week',
    description: 'Achieve 7 perfect days.',
    category: 'habits',
    rarity: 'rare',
    xp_reward: 100,
    condition: { type: 'perfect_days', threshold: 7 },
  },
  {
    id: 'perfect_30',
    icon: '🏆',
    title: 'Perfect Month',
    description: 'Achieve 30 perfect days.',
    category: 'habits',
    rarity: 'legendary',
    xp_reward: 500,
    condition: { type: 'perfect_days', threshold: 30 },
  },

  // ── XP / LEVEL ───────────────────────────────────────────────
  {
    id: 'xp_500',
    icon: '🥈',
    title: 'Silver Status',
    description: 'Reach Silver level (500 XP).',
    category: 'xp',
    rarity: 'common',
    xp_reward: 0,  // no bonus — the level is the reward
    condition: { type: 'total_xp', threshold: 500 },
  },
  {
    id: 'xp_1200',
    icon: '🥇',
    title: 'Gold Status',
    description: 'Reach Gold level (1,200 XP).',
    category: 'xp',
    rarity: 'rare',
    xp_reward: 0,
    condition: { type: 'total_xp', threshold: 1200 },
  },
  {
    id: 'xp_2500',
    icon: '💎',
    title: 'Diamond Status',
    description: 'Reach Diamond level (2,500 XP).',
    category: 'xp',
    rarity: 'epic',
    xp_reward: 0,
    condition: { type: 'total_xp', threshold: 2500 },
  },
  {
    id: 'xp_4000',
    icon: '👑',
    title: 'King Status',
    description: 'Reach King level (4,000 XP).',
    category: 'xp',
    rarity: 'legendary',
    xp_reward: 0,
    condition: { type: 'total_xp', threshold: 4000 },
  },

  // ── FOCUS / POMODORO ─────────────────────────────────────────
  {
    id: 'pomodoro_1',
    icon: '⏱️',
    title: 'First Focus',
    description: 'Complete your first Pomodoro session.',
    category: 'focus',
    rarity: 'common',
    xp_reward: 15,
    condition: { type: 'pomodoro_sessions', threshold: 1 },
  },
  {
    id: 'pomodoro_10',
    icon: '🎯',
    title: 'Deep Worker',
    description: 'Complete 10 Pomodoro sessions.',
    category: 'focus',
    rarity: 'rare',
    xp_reward: 60,
    condition: { type: 'pomodoro_sessions', threshold: 10 },
  },
  {
    id: 'pomodoro_50',
    icon: '🧠',
    title: 'Focus Machine',
    description: 'Complete 50 Pomodoro sessions.',
    category: 'focus',
    rarity: 'epic',
    xp_reward: 200,
    condition: { type: 'pomodoro_sessions', threshold: 50 },
  },
  {
    id: 'pomodoro_100',
    icon: '🏔️',
    title: 'Pomodoro Master',
    description: 'Complete 100 Pomodoro sessions.',
    category: 'focus',
    rarity: 'legendary',
    xp_reward: 500,
    condition: { type: 'pomodoro_sessions', threshold: 100 },
  },

  // ── WELLNESS ─────────────────────────────────────────────────
  {
    id: 'water_7',
    icon: '💧',
    title: 'Hydration Habit',
    description: 'Meet your water goal 7 days in a row.',
    category: 'wellness',
    rarity: 'rare',
    xp_reward: 75,
    condition: { type: 'water_days', threshold: 7 },
  },
  {
    id: 'water_30',
    icon: '🌊',
    title: 'Hydration Champion',
    description: 'Meet your water goal 30 days in a row.',
    category: 'wellness',
    rarity: 'epic',
    xp_reward: 250,
    condition: { type: 'water_days', threshold: 30 },
  },
  {
    id: 'checkin_7',
    icon: '📋',
    title: 'Self Aware',
    description: 'Log a daily check-in 7 days in a row.',
    category: 'wellness',
    rarity: 'rare',
    xp_reward: 75,
    condition: { type: 'checkin_days', threshold: 7 },
  },
  {
    id: 'checkin_30',
    icon: '🧘',
    title: 'Mind & Body',
    description: 'Log a daily check-in 30 days in a row.',
    category: 'wellness',
    rarity: 'epic',
    xp_reward: 200,
    condition: { type: 'checkin_days', threshold: 30 },
  },

  // ── MASTERY ──────────────────────────────────────────────────
  {
    id: 'habits_added_5',
    icon: '🗂️',
    title: 'System Builder',
    description: 'Add 5 or more habits to your routine.',
    category: 'mastery',
    rarity: 'common',
    xp_reward: 25,
    condition: { type: 'habits_added', threshold: 5 },
  },
  {
    id: 'challenge_1',
    icon: '🎖️',
    title: 'Challenge Accepted',
    description: 'Complete your first challenge.',
    category: 'mastery',
    rarity: 'rare',
    xp_reward: 100,
    condition: { type: 'challenges_completed', threshold: 1 },
  },
  {
    id: 'challenge_3',
    icon: '⚡',
    title: 'Challenge Dominator',
    description: 'Complete 3 challenges.',
    category: 'mastery',
    rarity: 'epic',
    xp_reward: 300,
    condition: { type: 'challenges_completed', threshold: 3 },
  },
  {
    id: 'weekly_perfect_1',
    icon: '🌟',
    title: 'Flawless Week',
    description: 'Complete every habit for 7 days straight.',
    category: 'mastery',
    rarity: 'epic',
    xp_reward: 200,
    condition: { type: 'weekly_perfect', threshold: 1 },
  },
]

// Quick lookup map
export const ACHIEVEMENT_MAP = new Map(ACHIEVEMENTS.map(a => [a.id, a]))

// Rarity display config
export const RARITY_CONFIG: Record<AchievementRarity, { label: string; color: string; glow: string }> = {
  common:    { label: 'Common',    color: '#94a3b8', glow: 'rgba(148,163,184,0.3)' },
  rare:      { label: 'Rare',      color: '#60a5fa', glow: 'rgba(96,165,250,0.35)' },
  epic:      { label: 'Epic',      color: '#a78bfa', glow: 'rgba(167,139,250,0.4)' },
  legendary: { label: 'Legendary', color: '#f59e0b', glow: 'rgba(245,158,11,0.45)' },
}
